# Création d'un wilder
POST http://localhost:5000/wilders
Content-Type: application/json

{
    "name": "Joffrey",
    "bio": "Ceci et le premier create :)",
    "city": "Bordeaux (33)"
}

###

# Liste de tout les Wilders
GET http://localhost:5000/wilders
Content-Type: application/json

###

# Retrouver un Wilder par son ID
GET http://localhost:5000/wilders/6
Content-Type: application/json


###

# Mettre à jour un wilder
PATCH http://localhost:5000/wilders/28
Content-Type: application/json

{
  "name":"test2",
  "city":"test2",
  "bio": "test2"
}

###

# Supprimer un Wilder
DELETE http://localhost:5000/wilders/30
Content-Type: application/json

###

# Ajout d'un skill à un wilder
POST http://localhost:5000/wilders/1/skills
Content-Type: application/json

{
    "id": 4
}

###

# Suppression d'un skill à un wilder
DELETE  http://localhost:5000/wilders/28/skills/1
Content-Type: application/json
